language: cpp
dist: bionic
compiler:
  - clang
  - gcc

script:
  - test "$CC" = "clang" && export CXX_FLAGS="-stdlib=libc++ -lc++fs" || true
  - cmake -DCMAKE_CXX_FLAGS="$CXX_FLAGS" .
  - cmake --build .
